CREATE TABLE [hr].[company] (
    [company]          INT            IDENTITY (1, 1) NOT NULL,
    [name]             NVARCHAR (150) NOT NULL,
    [registration_no]  NVARCHAR (30)  NOT NULL,
    [branch]           NVARCHAR (20)  NOT NULL,
    [address]          NVARCHAR (255) NOT NULL,
    [city]             NVARCHAR (15)  NOT NULL,
    [state]            NVARCHAR (20)  NOT NULL,
    [postcode]         NVARCHAR (10)  NOT NULL,
    [country]          NVARCHAR (2)   NOT NULL,
    [phone1]           NVARCHAR (20)  NOT NULL,
    [phone2]           NVARCHAR (20)  NOT NULL,
    [phone3]           NVARCHAR (20)  NOT NULL,
    [email1]           NVARCHAR (100) NOT NULL,
    [email2]           NVARCHAR (100) NOT NULL,
    [email3]           NVARCHAR (100) NOT NULL,
    [url]              NVARCHAR (255) NOT NULL,
    [fax1]             NVARCHAR (50)  NOT NULL,
    [fax2]             NVARCHAR (50)  NOT NULL,
    [remarks]          NVARCHAR (255) NOT NULL,
    [created_datetime] DATETIME2 (0)  CONSTRAINT [DF_business_created_datetime] DEFAULT (sysdatetime()) NOT NULL,
    [created_by]       INT            NOT NULL,
    CONSTRAINT [PK_business] PRIMARY KEY CLUSTERED ([company] ASC),
    CONSTRAINT [FK_business_country] FOREIGN KEY ([country]) REFERENCES [hr].[country] ([country]),
    CONSTRAINT [FK_business_user] FOREIGN KEY ([created_by]) REFERENCES [dbsecurity].[user] ([user]),
    CONSTRAINT [IX_business] UNIQUE NONCLUSTERED ([registration_no] ASC)
);

