CREATE TABLE [hr].[person] (
    [person]           INT            IDENTITY (1, 1) NOT NULL,
    [name]             NVARCHAR (100) NOT NULL,
    [ic_no]            NVARCHAR (50)  NOT NULL,
    [title]            NVARCHAR (5)   NOT NULL,
    [driving_license]  NVARCHAR (15)  NOT NULL,
    [gender]           NVARCHAR (10)  NOT NULL,
    [race]             NVARCHAR (10)  NOT NULL,
    [address]          NVARCHAR (255) NOT NULL,
    [city]             NVARCHAR (15)  NOT NULL,
    [state]            NVARCHAR (20)  NOT NULL,
    [postcode]         NVARCHAR (10)  NOT NULL,
    [country]          NVARCHAR (2)   NOT NULL,
    [phone1]           NVARCHAR (20)  NOT NULL,
    [phone2]           NVARCHAR (20)  NOT NULL,
    [email1]           NVARCHAR (100) NOT NULL,
    [email2]           NVARCHAR (100) NOT NULL,
    [occupation]       NVARCHAR (50)  NOT NULL,
    [company]          INT            NOT NULL,
    [remarks]          NVARCHAR (255) NOT NULL,
    [created_datetime] DATETIME2 (0)  CONSTRAINT [DF_people_created_datetime] DEFAULT (sysdatetime()) NOT NULL,
    [created_by]       INT            NOT NULL,
    CONSTRAINT [PK_people] PRIMARY KEY CLUSTERED ([person] ASC),
    CONSTRAINT [FK_people_company] FOREIGN KEY ([company]) REFERENCES [hr].[company] ([company]),
    CONSTRAINT [FK_people_country] FOREIGN KEY ([country]) REFERENCES [hr].[country] ([country]),
    CONSTRAINT [FK_people_user] FOREIGN KEY ([created_by]) REFERENCES [dbsecurity].[user] ([user]),
    CONSTRAINT [IX_people] UNIQUE NONCLUSTERED ([ic_no] ASC)
);

