CREATE TABLE [hr].[salesman] (
    [salesman]                 INT            IDENTITY (1, 1) NOT NULL,
    [person]                   INT            NULL,
    [company]                  INT            NULL,
    [location]                 NVARCHAR (255) CONSTRAINT [DF_salesman_location] DEFAULT ('') NOT NULL,
    [is_active]                BIT            CONSTRAINT [DF_salesman_is_active] DEFAULT ((1)) NOT NULL,
    [date_join]                DATE           CONSTRAINT [DF_salesman_date_join] DEFAULT (sysdatetime()) NOT NULL,
    [date_leave]               DATE           CONSTRAINT [DF_salesman_date_leave] DEFAULT (NULL) NULL,
    [sales_target1]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan] DEFAULT ((0)) NOT NULL,
    [sales_target2]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan11] DEFAULT ((0)) NOT NULL,
    [sales_target3]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan10] DEFAULT ((0)) NOT NULL,
    [sales_target4]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan9] DEFAULT ((0)) NOT NULL,
    [sales_target5]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan8] DEFAULT ((0)) NOT NULL,
    [sales_target6]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan7] DEFAULT ((0)) NOT NULL,
    [sales_target7]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan6] DEFAULT ((0)) NOT NULL,
    [sales_target8]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan5] DEFAULT ((0)) NOT NULL,
    [sales_target9]            FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan4] DEFAULT ((0)) NOT NULL,
    [sales_target10]           FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan3] DEFAULT ((0)) NOT NULL,
    [sales_target11]           FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan2] DEFAULT ((0)) NOT NULL,
    [sales_target12]           FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_jan1] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target1]  FLOAT (53)     CONSTRAINT [DF_salesman_sales_target_dec1] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target2]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan11] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target3]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan1] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target4]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan4] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target5]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan113] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target6]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan14] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target7]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan3] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target8]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan112] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target9]  FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan13] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target10] FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan2] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target11] FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan111] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target12] FLOAT (53)     CONSTRAINT [DF_salesman_insurance_renew_target_jan12] DEFAULT ((0)) NOT NULL,
    [created_by]               INT            NOT NULL,
    [created_datetime]         DATETIME2 (0)  CONSTRAINT [DF_salesman_created_datetime] DEFAULT (sysdatetime()) NOT NULL,
    CONSTRAINT [PK_salesman] PRIMARY KEY CLUSTERED ([salesman] ASC),
    CONSTRAINT [CK_salesman] CHECK ([person] IS NULL AND [company] IS NOT NULL OR [person] IS NOT NULL AND [company] IS NULL),
    CONSTRAINT [FK_salesman_company] FOREIGN KEY ([company]) REFERENCES [hr].[company] ([company]),
    CONSTRAINT [FK_salesman_person] FOREIGN KEY ([person]) REFERENCES [hr].[person] ([person]),
    CONSTRAINT [FK_salesman_user] FOREIGN KEY ([created_by]) REFERENCES [dbsecurity].[user] ([user]),
    CONSTRAINT [IX_salesman] UNIQUE NONCLUSTERED ([person] ASC, [company] ASC)
);

