CREATE TABLE [fin].[vehicle_sale] (
    [vehicle]                          INT             IDENTITY (1, 1) NOT NULL,
    [reference_no_prefix]              NVARCHAR (5)    CONSTRAINT [DF_vehicle_sale_reference_no_prefix] DEFAULT ('') NOT NULL,
    [reference_no]                     AS              ([reference_no_prefix]+CONVERT([nvarchar],[vehicle])),
    [customer_person]                  INT             NULL,
    [customer_organisation_branch]     INT             NULL,
    [sale_date]                        DATE            NOT NULL,
    [sale_price]                       DECIMAL (18, 4) NOT NULL,
    [road_tax_amount]                  DECIMAL (18, 4) NOT NULL,
    [road_tax_month]                   TINYINT         NOT NULL,
    [loan]                             INT             NULL,
    [loan_amount]                      DECIMAL (18, 4) NULL,
    [loan_month_term]                  TINYINT         NULL,
    [loan_interest_percentage]         TINYINT         NULL,
    [loan_monthly_installment]         DECIMAL (18, 4) NULL,
    [loan_ref_no]                      NVARCHAR (50)   NULL,
    [loan_approval_date]               DATE            NULL,
    [loan_commission]                  DECIMAL (18, 4) NULL,
    [loan_ownership_claim_no]          NVARCHAR (50)   NULL,
    [guarantor_person]                 INT             NULL,
    [insurance]                        INT             NULL,
    [insurance_cover_note_no]          NVARCHAR (50)   NULL,
    [insurance_endorsement_no]         NVARCHAR (50)   NULL,
    [insurance_policy_no]              NVARCHAR (50)   NULL,
    [insurance_date]                   DATE            NULL,
    [insurance_category]               INT             NULL,
    [insurance_type]                   TINYINT         NULL,
    [insurance_sum_insured]            DECIMAL (18, 4) NOT NULL,
    [insurance_premium]                DECIMAL (18, 4) NOT NULL,
    [insurance_stamp_duty]             DECIMAL (18, 4) NOT NULL,
    [insurance_loading_percent]        TINYINT         NOT NULL,
    [insurance_ncb_percent]            TINYINT         NOT NULL,
    [insurance_windscreen]             DECIMAL (18, 4) NOT NULL,
    [insurance_windscreen_sum_insured] DECIMAL (18, 4) NOT NULL,
    [salesperson]                      INT             NOT NULL,
    [remark]                           NVARCHAR (255)  NOT NULL,
    [modified_by]                      INT             NOT NULL,
    CONSTRAINT [PK_vehicle_sale_1] PRIMARY KEY CLUSTERED ([vehicle] ASC),
    CONSTRAINT [FK_vehicle_sale_insurance] FOREIGN KEY ([insurance]) REFERENCES [hr].[insurance] ([insurance]),
    CONSTRAINT [FK_vehicle_sale_insurance_category] FOREIGN KEY ([insurance_category]) REFERENCES [fin].[insurance_category] ([insurance_category]),
    CONSTRAINT [FK_vehicle_sale_loan] FOREIGN KEY ([loan]) REFERENCES [hr].[loan] ([loan]),
    CONSTRAINT [FK_vehicle_sale_organisation_branch] FOREIGN KEY ([customer_organisation_branch]) REFERENCES [hr].[organisation_branch] ([organisation_branch]),
    CONSTRAINT [FK_vehicle_sale_person] FOREIGN KEY ([customer_person]) REFERENCES [hr].[person] ([person]),
    CONSTRAINT [FK_vehicle_sale_person1] FOREIGN KEY ([guarantor_person]) REFERENCES [hr].[person] ([person]),
    CONSTRAINT [FK_vehicle_sale_salesperson] FOREIGN KEY ([salesperson]) REFERENCES [hr].[salesperson] ([salesperson]),
    CONSTRAINT [FK_vehicle_sale_user] FOREIGN KEY ([modified_by]) REFERENCES [dbsecurity].[user] ([user])
);





