CREATE TABLE [dbhistory].[salesperson] (
    [salesperson]              INT            NOT NULL,
    [person]                   INT            NULL,
    [company]                  INT            NULL,
    [location]                 NVARCHAR (255) CONSTRAINT [DF_salesperson_location] DEFAULT ('') NOT NULL,
    [is_active]                BIT            CONSTRAINT [DF_salesperson_is_active] DEFAULT ((1)) NOT NULL,
    [date_join]                DATE           CONSTRAINT [DF_salesperson_date_join] DEFAULT (sysdatetime()) NOT NULL,
    [date_leave]               DATE           CONSTRAINT [DF_salesperson_date_leave] DEFAULT (NULL) NULL,
    [sales_target1]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target1] DEFAULT ((0)) NOT NULL,
    [sales_target2]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target2] DEFAULT ((0)) NOT NULL,
    [sales_target3]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target3] DEFAULT ((0)) NOT NULL,
    [sales_target4]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target4] DEFAULT ((0)) NOT NULL,
    [sales_target5]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target5] DEFAULT ((0)) NOT NULL,
    [sales_target6]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target6] DEFAULT ((0)) NOT NULL,
    [sales_target7]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target7] DEFAULT ((0)) NOT NULL,
    [sales_target8]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target8] DEFAULT ((0)) NOT NULL,
    [sales_target9]            FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target9] DEFAULT ((0)) NOT NULL,
    [sales_target10]           FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target10] DEFAULT ((0)) NOT NULL,
    [sales_target11]           FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target11] DEFAULT ((0)) NOT NULL,
    [sales_target12]           FLOAT (53)     CONSTRAINT [DF_salesperson_sales_target12] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target1]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target1] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target2]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target2] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target3]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target3] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target4]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target4] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target5]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target5] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target6]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target6] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target7]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target7] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target8]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target8] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target9]  FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target9] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target10] FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target10] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target11] FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target11] DEFAULT ((0)) NOT NULL,
    [insurance_renew_target12] FLOAT (53)     CONSTRAINT [DF_salesperson_insurance_renew_target12] DEFAULT ((0)) NOT NULL,
    [modified_by]              INT            NOT NULL,
    [modified_on]              DATETIME2 (0)  CONSTRAINT [DF_salesperson_modified_on] DEFAULT (sysdatetime()) NOT NULL
);

